# Generated by Django 3.0.6 on 2020-10-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(2, '支付宝'), (1, '货到付款')], default=1, verbose_name='支付方式'),
        ),
    ]
